// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9rqOULy7nIk_TcXeNNZbMimXYwdq1aAY',
    appId: '1:258409193215:web:5ac584ecacb27b68bab6ca',
    messagingSenderId: '258409193215',
    projectId: 'pawfectmatch-f92dd',
    authDomain: 'pawfectmatch-f92dd.firebaseapp.com',
    storageBucket: 'pawfectmatch-f92dd.appspot.com',
    measurementId: 'G-8TZ01KNDP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoav52T9sKjkzvjAmttLJMAM2TP7oTyF4',
    appId: '1:258409193215:android:3de89c24c8e67853bab6ca',
    messagingSenderId: '258409193215',
    projectId: 'pawfectmatch-f92dd',
    storageBucket: 'pawfectmatch-f92dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAath__yk2_zoHK3uGcVnVMUS9amNsUJjo',
    appId: '1:258409193215:ios:3482e56e39ac2277bab6ca',
    messagingSenderId: '258409193215',
    projectId: 'pawfectmatch-f92dd',
    storageBucket: 'pawfectmatch-f92dd.appspot.com',
    iosBundleId: 'com.example.pawfectmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAath__yk2_zoHK3uGcVnVMUS9amNsUJjo',
    appId: '1:258409193215:ios:e1976fb6a465c7efbab6ca',
    messagingSenderId: '258409193215',
    projectId: 'pawfectmatch-f92dd',
    storageBucket: 'pawfectmatch-f92dd.appspot.com',
    iosBundleId: 'com.example.pawfectmatch.RunnerTests',
  );
}
