class DogBreeds {
  static final List<String> doglist = [
    'Aspin',
    'Shih Tzu',
    'Siberian Husky',
    'Pomeranian',
    'Chihuahua',
    'Beagle',
    'Dachshund',
    'Golden Retriever',
    'Labrador Retriever',
    'German Shepherd',
    'Doberman',
    'Boxer',
    'Rottweiler',
    'Poodle',
    'Bulldog',
    'Great Dane',
    'Dalmatian',
    'Cocker Spaniel',
    'Saint Bernard',
    'Pug',
    'Yorkshire Terrier',
    'Jack Russell Terrier',
    'Maltese',
    'French Bulldog',
    'Collie',
    'Boston Terrier',
    'Chow Chow',
    'Belgian Malinois',
    'Akita',
    'Bernese Mountain Dog',
    'Shiba Inu',
    'Bichon Frise',
    'Cairn Terrier',
    'English Bulldog',
    'Border Collie',
    'Afghan Hound',
    'Basenji',
    'Australian Shepherd',
    'Newfoundland',
    'Shih-Poo',
    'Miniature Schnauzer',
    'Italian Greyhound',
    'Irish Wolfhound',
    'Samoyed',
    'Alaskan Malamute',
    'Great Pyrenees',
    'Basset Hound',
    'Australian Terrier',
    'Bullmastiff',
    'Havanese',
    'Bolognese',
    'Silky Terrier',
    'Bull Terrier',
    'Old English Sheepdog',
    'Tibetan Mastiff',
    'Toy Poodle',
    'Borzoi',
    'English Springer Spaniel',
  ];

  static List<String> getSuggestions(String query) {
    List<String> matches = [];
    matches.addAll(doglist);
    matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}
